Добавляет наставника
htmlacademy-htmlcss/2109103-sedona-36 pull request #1
Opened 2023-01-18 04:39 UTC by UberSurale

2023-01-18 05:39 UTC, pavel-nyukalo requested changes

2023-01-18 05:39 UTC, pavel-nyukalo commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Добавь, пожалуйста, ссылку и на меня, по аналогии с твоей, то есть `[Текст](сама ссылка)`

Так же предлагаю текстовое общение вести в дискорде. Там все мои студенты, которые тоже могут помогать с возникающими вопросами

Вот [ссылка](https://discord.gg/sSeNxhfcKR)

2023-01-18 14:39 UTC, UberSurale commented on Readme.md
> +* Наставник: `Павел Нюкало`.
Понял, благодарю за фидбек, в дискорд зайду!

2023-01-19 05:53 UTC, pavel-nyukalo approved these changes

2023-01-19 05:54 UTC, merged