Добавляет верстку двух страниц Седоны
htmlacademy-htmlcss/2109103-sedona-36 pull request #2
Opened 2023-01-23 07:47 UTC by UberSurale

2023-01-23 15:43 UTC, pavel-nyukalo requested changes

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +        <a class="navigation-logo" href="#"><img src="" alt="Логотип Седона"></a>
Давай еще размеры добавим изображению, это нужно по критерию

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +            </a>
Скрытым подписям нужно добавлять точку в конце по критерию. Относится ко всем таким элементам

![image](https://user-images.githubusercontent.com/52506235/214080628-6ad23a8a-ce7e-493c-ac20-78142f6e49b7.png)

![image](https://user-images.githubusercontent.com/52506235/214080638-210529ba-b570-46ee-acc4-6a638b8ee17b.png)

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +          </li>
Их лучше не разделять на два разных пункта, ибо список у нас именно преимуществ. А картинки уже относятся к конкретным пунктам

Так что нужно картинку положить в первый `li`

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +          </li>
Тут так же

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +            <img src="" alt="Иконка дома" class="advantages-company-icon">
Эти картинки я бы предложил сделать декоративными, то есть делать через `css`. А из резметки убрать

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +        <button class="button book-hotel-button">Поиск гостиницы в Седоне</button>
Это у нас ссылка - она бы вела на страницу поиска например

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +      </section>
1. Я бы предложил этот блок тоже в футер положить, поскольку он есть на обоих страницах
2. Ошибка в написании `method`
3. И нужно добавить скрытый `label` для инпута, по критерию

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +          </a>
Дочерними тегами `ul` могут быть только теги `li`

![image](https://user-images.githubusercontent.com/52506235/214081503-fa7770b9-6145-4d4b-bd01-f4592d90accd.png)

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +        <adress class="contacts-adress">
Ошибка в написании `address`

2023-01-23 15:43 UTC, pavel-nyukalo commented on index.html
> +      <section class="footer-logo">
![image](https://user-images.githubusercontent.com/52506235/214082147-743e50be-c48b-461a-95d7-97070d5f5e67.png)

2023-01-23 15:43 UTC, pavel-nyukalo commented on catalog.html
> +      <select class="catalog-hotels-select-control" aria-lebel="Сортировка">
`aria-label`

2023-01-23 15:43 UTC, pavel-nyukalo commented on catalog.html
> +      </a>
Тут можно тоже сделать списком думаю

2023-01-23 15:43 UTC, pavel-nyukalo commented on catalog.html
> +        <button class="button" href="#">Избранное</button>
У кнопок нет должно быть атрибута `href`

2023-01-23 15:43 UTC, pavel-nyukalo commented on catalog.html
> +        <a class="hotel-card-review" href="#">
Рейтинг думаю на ссылку не очень похож

2023-01-23 15:43 UTC, pavel-nyukalo commented on catalog.html
> +      </span>
Аналогично про `ul` > `li`

2023-01-23 15:43 UTC, pavel-nyukalo commented on catalog.html
> +  </footer>
Тут те же замечания

2023-01-24 07:01 UTC, UberSurale commented on index.html
> +        <a class="navigation-logo" href="#"><img src="" alt="Логотип Седона"></a>
Хорошо! Но получается, что добавляем width и height только логотипу, потому что у нас в задании написано следующее:

![image](https://user-images.githubusercontent.com/104767006/214230649-47b0368b-037e-483d-8f3e-f3a68f0db237.png)

Правильно понял?

2023-01-24 07:04 UTC, UberSurale commented on index.html
> +        <button class="button book-hotel-button">Поиск гостиницы в Седоне</button>
Вот здесь немного запутался. У нас же поиск выполнен в виде модального окна и это не отдельная страница, а кнопки чаще для них и используют или я тут намудрил?

![image](https://user-images.githubusercontent.com/104767006/214231221-483442b6-f953-4832-8aed-57f654bf0e60.png)

2023-01-25 10:43 UTC, pavel-nyukalo requested changes

2023-01-25 10:43 UTC, pavel-nyukalo commented on catalog.html
> +<body>
Давай сделаем аналогично `index.html`, там у этих тегов есть отступ от `<html>`

![image](https://user-images.githubusercontent.com/52506235/214541986-dc9f6f06-9da4-47d4-84e9-0b73a08c3528.png)

И соответственно у `</body>` нужно будет поправить отступ

2023-01-25 10:43 UTC, pavel-nyukalo commented on catalog.html
> +        </label>
Тут нужно осторожно оборачивать инпут

`label` у нас с классом `visually-hidden` - этот класс у нас будет визуально скрывать элемент, оставляя его в дереве доступности 

Соответственно, если мы обернем в такой элемент инпут - он у нас просто скроется и все.
А нам важно что бы он был

Поэтому тут можно сделать так

```html
<label class="visually-hidden" for="input-id">Ваш E-mail</label>
<input id="input-id" type="email" name="subscription-email" placeholder="Ваш e-mail">
```

В index.html так же нужно сделать

2023-01-26 11:30 UTC, pavel-niukalo approved these changes

2023-01-26 11:30 UTC, merged